### ISSUE TITLE
Support for Assemblies

### ISSUE THREAD

**Issue by sabrehagen** [Autodesk-Forge/model.derivative-nodejs-google.drive.viewer#1]
Hi,

When trying to translate assemblies using your sample, they fail. How do you suggest one would render assemblies using the Autodesk API and Google Drive?

Best,
Jackson

**Comment by augustogoncalves** [comment]
This sample implements the following workflow: authorize your Google Account, allow you to select a file there, download and upload to Autodesk (Forge Bucket) then, finally, translate it. The original file on Autodesk is deleted right after. 

If you have an assembly (I'm assuming a Inventor one) with dependencies (other parts) then this workflow is not implemented. For that you'll need to prepare a .zip file with everything you need (assemblies and parts) and submit for translation specifying the root file (the root assembly).
