### ISSUE TITLE
502 (Bad Gateway) Error

### ISSUE THREAD

**Issue by gaparicio** [Autodesk-Forge/model.derivative-nodejs-google.drive.viewer#2]
Geeting a https://google-drive-viewer-gaparicio.c9users.io/google/getTreeNode?id=%23 502 (Bad Gateway) Error when logging into Google account and getting hung on loading.

**Comment by gaparicio** [comment]
Apparently, setCredentials is no longer a function in v23 so you need to change 

oauth2Client.setCredentials({
     access_token: tokenSession.getGoogleToken()
    });

to 

    oauth2Client.credentials = ({access_token: tokenSession.getGoogleToken()});

**Comment by augustogoncalves** [comment]
Yes, you're correct, thanks for that. For now I have changed the package to use Google v19
