### ISSUE TITLE
not working on localhost

### ISSUE THREAD

**Issue by douglaspetrin** [Autodesk-Forge/model.derivative-nodejs-google.drive.viewer#3]
Hi

I can access the google drive, but when I click on the file to open in the app, it does not load and in the terminal it says: { statusCode: 403, statusMessage: 'Unauthorized' }

what could it be?

**Comment by augustogoncalves** [comment]
hum... interesting... I guess there is a bug at https://github.com/Autodesk-Forge/model.derivative-nodejs-google.drive.viewer/blob/master/server/model.derivative.google.drive.integration.js#L65, it should name the bucket with a prefix (e.g. your client ID) to avoid duplicated names across apps...

cannot test right now, but this should do the trick:

```
var ossBucketKey =  config.credentials.client_id + (user.displayName.replace(/\W+/g, '') + user.id).toLowerCase();
```

**Comment by douglaspetrin** [comment]
@augustogoncalves Sorry but this issue is happening to the app I've deployed at Heroku as well. It might be related to google apis. I've created the credentials, I activated the google people api, google+ and drive api. 

![image](https://user-images.githubusercontent.com/36938293/41790403-e106ce70-7628-11e8-9f90-61850fda6dc6.png)


Idk what I am doing wrong. Do you think am I setting the google api wrong? Do you have a tuto how to set the api for this app?

**Comment by augustogoncalves** [comment]
just committed a change that fixes this issue, please take a look, @douglaspetrin

**Comment by douglaspetrin** [comment]
@augustogoncalves thanks! Now it's working.
