### ISSUE TITLE
Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by douglaspetrin** [Autodesk-Forge/model.derivative-nodejs-google.drive.viewer#4]
I am trying to run the app on dreamhost, but when try to login via google it says:

400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:3000/api/google/callback/oauth, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs

I already set the credentials on google, but how can I change the "http://localhost:3000/api/google/callback/oauth" to mine url in the app, like "http://mywebsite.com:3000/api/google/callback/oauth ?

**Comment by augustogoncalves** [comment]
the URL on this app should be exactly the same on your Google Console API.

on the app, check the config file: https://github.com/Autodesk-Forge/model.derivative-nodejs-google.drive.viewer/blob/master/server/config.js#L41

**Comment by douglaspetrin** [comment]
Thanks!

But now, for no reason it's saying:

> node start.js

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)

 at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 3.14.52-vs2.3.6.15-1
npm ERR! argv "/usr/local/dh/nodejs/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! model.derivative-nodejs-box.viewer@1.0.0 dev: `node start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the model.derivative-nodejs-box.viewer@1.0.0 dev script 'node start.js'.
npm ERR! This is most likely a problem with the model.derivative-nodejs-box.viewer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls model.derivative-nodejs-box.viewer
npm ERR! There is likely additional logging output above.

**Comment by augustogoncalves** [comment]
usually `EADDRINUSE` means some other nodejs process is using the same PORT (i.e. 3000). make sure to kill other nodejs processes.

**Comment by douglaspetrin** [comment]
I killed, it worked. But when I tried to open a dwg or rvt file it said:

node_modules/forge-apis/src/auth/OAuth2TwoLegged.js:115
                    var credentials = Object.assign({}, response,
                                             ^
TypeError: undefined is not a function

**Comment by augustogoncalves** [comment]
not sure what that is, have you specified all settings on config.js file?

you may also try to delete the node_modules folder and `npm install` again.

**Comment by douglaspetrin** [comment]
yes, I specified all settings on config.js, deleted node_modules folder and npm install and the same error happened. 

Should I export FORGE_CLIENT_ID= ; export FORGE_CLIENT_SECRET=.... even setting config.js?

**Comment by augustogoncalves** [comment]
you need the client id/secret on env var or hardcoded on the config.js (one or the other)
